### ISSUE TITLE
cypress.config.ts export error

### ISSUE THREAD

**Issue by jauntyjocularjay** [Idrinth/api-bench#916]
## Describe the bug

There appears to be a syntax error thrown on the export keyword in cypress.config.ts

## To Reproduce

1. Open cypress
2. Click on e2e
3. See error

## Expected behavior

Cypress should open and be able to run tests

## Screenshots

```bash
Your configFile is invalid: ~\OneDrive\Workspace\Programming\JSTS\Cypress\api-bench\cypress.config.ts

It threw an error when required, check the stack trace below:

..\..\..\..\..\..\..\..\Cypress\Cache\13.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14
  87 |       debug('Loading file %s', file)
  88 | 
> 89 |       return require(file)
     |              ^
  90 |     } catch (err) {
  91 |       if (!err.stack.includes('[ERR_REQUIRE_ESM]') && !err.stack.includes('SyntaxError: Cannot use import statement outside a module')) {
  92 |         throw err
  93 |       }
[Stack trace](http://localhost:63570/__launchpad/index.html#)
~\OneDrive\Workspace\Programming\JSTS\Cypress\api-bench\cypress.config.ts:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at loadFile (~\AppData\Local\Cypress\Cache\13.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter. (~\AppData\Local\Cypress\Cache\13.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:519:28)
  at process. (~\AppData\Local\Cypress\Cache\13.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

## System

please complete the following information:

- OS: Windows 10
- Version: builds 19045

## Additional context

n/a

**Comment by Idrinth** [comment]
This config is in the wrong folder, not a project issue.
